
pipeline {
    agent any
    
    stages {
        
        stage('delete origin zip file'){
            steps{
                script{
                    try{
                        
                        sh'rm -rf *.zip' 
                    } catch(error){
                        print(error)
                        env.cloneResult = false
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }
        stage('Build Test'){
            steps{
                script{
                    try{
                        String currentDirectory = pwd()
                        sh 'zip -r JenkinsTest/${BUILD_NUMBER}'
                    } catch(error){
                        print(error)
                        env.cloneResult = false
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }        
    }
}
