#!/bin/sh
ssh ubuntu@ip-172-31-44-105<<EOF
cd ~/JenkinsTest
git pull origin main
curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
. ~/.nvm/nvm.sh 
nvm install 16.17.0
npm install
npm install -g pm2
pm2 restart app
exit
EOF